/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSubscriptionsRouteImport } from './routes/api/subscriptions'
import { Route as ApiSettingsRouteImport } from './routes/api/settings'
import { Route as ApiProvidersRouteImport } from './routes/api/providers'
import { Route as ApiProductsRouteImport } from './routes/api/products'
import { Route as ApiPaymentsRouteImport } from './routes/api/payments'
import { Route as ApiInvoicesRouteImport } from './routes/api/invoices'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiAuditRouteImport } from './routes/api/audit'
import { Route as ApiWebhooksSubscribersRouteImport } from './routes/api/webhooks/subscribers'
import { Route as ApiWebhooksStripeRouteImport } from './routes/api/webhooks/stripe'
import { Route as ApiSubscriptionsIdRouteImport } from './routes/api/subscriptions/$id'
import { Route as ApiProvidersIdRouteImport } from './routes/api/providers/$id'
import { Route as ApiProductsIdRouteImport } from './routes/api/products/$id'
import { Route as ApiMySubscriptionsRouteImport } from './routes/api/my/subscriptions'
import { Route as ApiMySubscribeRouteImport } from './routes/api/my/subscribe'
import { Route as ApiMyInvoicesRouteImport } from './routes/api/my/invoices'
import { Route as ApiInvoicesIdRouteImport } from './routes/api/invoices/$id'
import { Route as ApiWebhooksSubscribersIdRouteImport } from './routes/api/webhooks/subscribers/$id'
import { Route as ApiProvidersIdSettingsRouteImport } from './routes/api/providers/$id/settings'
import { Route as ApiProvidersIdDeactivateRouteImport } from './routes/api/providers/$id/deactivate'
import { Route as ApiProvidersIdActivateRouteImport } from './routes/api/providers/$id/activate'
import { Route as ApiProvidersIdActionsRouteImport } from './routes/api/providers/$id/actions'
import { Route as ApiProductsIdToggleRouteImport } from './routes/api/products/$id/toggle'
import { Route as ApiProductsIdActionsRouteImport } from './routes/api/products/$id/actions'
import { Route as ApiMyInvoicesIdRouteImport } from './routes/api/my/invoices/$id'
import { Route as ApiInvoicesIdStatusRouteImport } from './routes/api/invoices/$id/status'
import { Route as ApiInvoicesIdRefundRouteImport } from './routes/api/invoices/$id/refund'
import { Route as ApiInvoicesIdMarkPaidRouteImport } from './routes/api/invoices/$id/mark-paid'
import { Route as ApiInvoicesIdItemsRouteImport } from './routes/api/invoices/$id/items'
import { Route as ApiInvoicesIdCancelRouteImport } from './routes/api/invoices/$id/cancel'
import { Route as ApiInvoicesIdActionsRouteImport } from './routes/api/invoices/$id/actions'
import { Route as ApiWebhooksSubscribersIdToggleRouteImport } from './routes/api/webhooks/subscribers/$id/toggle'
import { Route as ApiWebhooksSubscribersIdActionsRouteImport } from './routes/api/webhooks/subscribers/$id/actions'
import { Route as ApiMySubscriptionsIdCancelRouteImport } from './routes/api/my/subscriptions/$id/cancel'
import { Route as ApiMyInvoicesIdPayRouteImport } from './routes/api/my/invoices/$id/pay'
import { Route as ApiMyInvoicesIdItemsRouteImport } from './routes/api/my/invoices/$id/items'
import { Route as ApiMyInvoicesIdActionsRouteImport } from './routes/api/my/invoices/$id/actions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubscriptionsRoute = ApiSubscriptionsRouteImport.update({
  id: '/api/subscriptions',
  path: '/api/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsRoute = ApiSettingsRouteImport.update({
  id: '/api/settings',
  path: '/api/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProvidersRoute = ApiProvidersRouteImport.update({
  id: '/api/providers',
  path: '/api/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsRoute = ApiProductsRouteImport.update({
  id: '/api/products',
  path: '/api/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsRoute = ApiPaymentsRouteImport.update({
  id: '/api/payments',
  path: '/api/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvoicesRoute = ApiInvoicesRouteImport.update({
  id: '/api/invoices',
  path: '/api/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuditRoute = ApiAuditRouteImport.update({
  id: '/api/audit',
  path: '/api/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksSubscribersRoute = ApiWebhooksSubscribersRouteImport.update({
  id: '/api/webhooks/subscribers',
  path: '/api/webhooks/subscribers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/api/webhooks/stripe',
  path: '/api/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubscriptionsIdRoute = ApiSubscriptionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiSubscriptionsRoute,
} as any)
const ApiProvidersIdRoute = ApiProvidersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiProvidersRoute,
} as any)
const ApiProductsIdRoute = ApiProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiProductsRoute,
} as any)
const ApiMySubscriptionsRoute = ApiMySubscriptionsRouteImport.update({
  id: '/api/my/subscriptions',
  path: '/api/my/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMySubscribeRoute = ApiMySubscribeRouteImport.update({
  id: '/api/my/subscribe',
  path: '/api/my/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMyInvoicesRoute = ApiMyInvoicesRouteImport.update({
  id: '/api/my/invoices',
  path: '/api/my/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvoicesIdRoute = ApiInvoicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiInvoicesRoute,
} as any)
const ApiWebhooksSubscribersIdRoute =
  ApiWebhooksSubscribersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ApiWebhooksSubscribersRoute,
  } as any)
const ApiProvidersIdSettingsRoute = ApiProvidersIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ApiProvidersIdRoute,
} as any)
const ApiProvidersIdDeactivateRoute =
  ApiProvidersIdDeactivateRouteImport.update({
    id: '/deactivate',
    path: '/deactivate',
    getParentRoute: () => ApiProvidersIdRoute,
  } as any)
const ApiProvidersIdActivateRoute = ApiProvidersIdActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => ApiProvidersIdRoute,
} as any)
const ApiProvidersIdActionsRoute = ApiProvidersIdActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => ApiProvidersIdRoute,
} as any)
const ApiProductsIdToggleRoute = ApiProductsIdToggleRouteImport.update({
  id: '/toggle',
  path: '/toggle',
  getParentRoute: () => ApiProductsIdRoute,
} as any)
const ApiProductsIdActionsRoute = ApiProductsIdActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => ApiProductsIdRoute,
} as any)
const ApiMyInvoicesIdRoute = ApiMyInvoicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiMyInvoicesRoute,
} as any)
const ApiInvoicesIdStatusRoute = ApiInvoicesIdStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => ApiInvoicesIdRoute,
} as any)
const ApiInvoicesIdRefundRoute = ApiInvoicesIdRefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => ApiInvoicesIdRoute,
} as any)
const ApiInvoicesIdMarkPaidRoute = ApiInvoicesIdMarkPaidRouteImport.update({
  id: '/mark-paid',
  path: '/mark-paid',
  getParentRoute: () => ApiInvoicesIdRoute,
} as any)
const ApiInvoicesIdItemsRoute = ApiInvoicesIdItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => ApiInvoicesIdRoute,
} as any)
const ApiInvoicesIdCancelRoute = ApiInvoicesIdCancelRouteImport.update({
  id: '/cancel',
  path: '/cancel',
  getParentRoute: () => ApiInvoicesIdRoute,
} as any)
const ApiInvoicesIdActionsRoute = ApiInvoicesIdActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => ApiInvoicesIdRoute,
} as any)
const ApiWebhooksSubscribersIdToggleRoute =
  ApiWebhooksSubscribersIdToggleRouteImport.update({
    id: '/toggle',
    path: '/toggle',
    getParentRoute: () => ApiWebhooksSubscribersIdRoute,
  } as any)
const ApiWebhooksSubscribersIdActionsRoute =
  ApiWebhooksSubscribersIdActionsRouteImport.update({
    id: '/actions',
    path: '/actions',
    getParentRoute: () => ApiWebhooksSubscribersIdRoute,
  } as any)
const ApiMySubscriptionsIdCancelRoute =
  ApiMySubscriptionsIdCancelRouteImport.update({
    id: '/$id/cancel',
    path: '/$id/cancel',
    getParentRoute: () => ApiMySubscriptionsRoute,
  } as any)
const ApiMyInvoicesIdPayRoute = ApiMyInvoicesIdPayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => ApiMyInvoicesIdRoute,
} as any)
const ApiMyInvoicesIdItemsRoute = ApiMyInvoicesIdItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => ApiMyInvoicesIdRoute,
} as any)
const ApiMyInvoicesIdActionsRoute = ApiMyInvoicesIdActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => ApiMyInvoicesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/audit': typeof ApiAuditRoute
  '/api/health': typeof ApiHealthRoute
  '/api/invoices': typeof ApiInvoicesRouteWithChildren
  '/api/payments': typeof ApiPaymentsRoute
  '/api/products': typeof ApiProductsRouteWithChildren
  '/api/providers': typeof ApiProvidersRouteWithChildren
  '/api/settings': typeof ApiSettingsRoute
  '/api/subscriptions': typeof ApiSubscriptionsRouteWithChildren
  '/api/invoices/$id': typeof ApiInvoicesIdRouteWithChildren
  '/api/my/invoices': typeof ApiMyInvoicesRouteWithChildren
  '/api/my/subscribe': typeof ApiMySubscribeRoute
  '/api/my/subscriptions': typeof ApiMySubscriptionsRouteWithChildren
  '/api/products/$id': typeof ApiProductsIdRouteWithChildren
  '/api/providers/$id': typeof ApiProvidersIdRouteWithChildren
  '/api/subscriptions/$id': typeof ApiSubscriptionsIdRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/api/webhooks/subscribers': typeof ApiWebhooksSubscribersRouteWithChildren
  '/api/invoices/$id/actions': typeof ApiInvoicesIdActionsRoute
  '/api/invoices/$id/cancel': typeof ApiInvoicesIdCancelRoute
  '/api/invoices/$id/items': typeof ApiInvoicesIdItemsRoute
  '/api/invoices/$id/mark-paid': typeof ApiInvoicesIdMarkPaidRoute
  '/api/invoices/$id/refund': typeof ApiInvoicesIdRefundRoute
  '/api/invoices/$id/status': typeof ApiInvoicesIdStatusRoute
  '/api/my/invoices/$id': typeof ApiMyInvoicesIdRouteWithChildren
  '/api/products/$id/actions': typeof ApiProductsIdActionsRoute
  '/api/products/$id/toggle': typeof ApiProductsIdToggleRoute
  '/api/providers/$id/actions': typeof ApiProvidersIdActionsRoute
  '/api/providers/$id/activate': typeof ApiProvidersIdActivateRoute
  '/api/providers/$id/deactivate': typeof ApiProvidersIdDeactivateRoute
  '/api/providers/$id/settings': typeof ApiProvidersIdSettingsRoute
  '/api/webhooks/subscribers/$id': typeof ApiWebhooksSubscribersIdRouteWithChildren
  '/api/my/invoices/$id/actions': typeof ApiMyInvoicesIdActionsRoute
  '/api/my/invoices/$id/items': typeof ApiMyInvoicesIdItemsRoute
  '/api/my/invoices/$id/pay': typeof ApiMyInvoicesIdPayRoute
  '/api/my/subscriptions/$id/cancel': typeof ApiMySubscriptionsIdCancelRoute
  '/api/webhooks/subscribers/$id/actions': typeof ApiWebhooksSubscribersIdActionsRoute
  '/api/webhooks/subscribers/$id/toggle': typeof ApiWebhooksSubscribersIdToggleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/audit': typeof ApiAuditRoute
  '/api/health': typeof ApiHealthRoute
  '/api/invoices': typeof ApiInvoicesRouteWithChildren
  '/api/payments': typeof ApiPaymentsRoute
  '/api/products': typeof ApiProductsRouteWithChildren
  '/api/providers': typeof ApiProvidersRouteWithChildren
  '/api/settings': typeof ApiSettingsRoute
  '/api/subscriptions': typeof ApiSubscriptionsRouteWithChildren
  '/api/invoices/$id': typeof ApiInvoicesIdRouteWithChildren
  '/api/my/invoices': typeof ApiMyInvoicesRouteWithChildren
  '/api/my/subscribe': typeof ApiMySubscribeRoute
  '/api/my/subscriptions': typeof ApiMySubscriptionsRouteWithChildren
  '/api/products/$id': typeof ApiProductsIdRouteWithChildren
  '/api/providers/$id': typeof ApiProvidersIdRouteWithChildren
  '/api/subscriptions/$id': typeof ApiSubscriptionsIdRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/api/webhooks/subscribers': typeof ApiWebhooksSubscribersRouteWithChildren
  '/api/invoices/$id/actions': typeof ApiInvoicesIdActionsRoute
  '/api/invoices/$id/cancel': typeof ApiInvoicesIdCancelRoute
  '/api/invoices/$id/items': typeof ApiInvoicesIdItemsRoute
  '/api/invoices/$id/mark-paid': typeof ApiInvoicesIdMarkPaidRoute
  '/api/invoices/$id/refund': typeof ApiInvoicesIdRefundRoute
  '/api/invoices/$id/status': typeof ApiInvoicesIdStatusRoute
  '/api/my/invoices/$id': typeof ApiMyInvoicesIdRouteWithChildren
  '/api/products/$id/actions': typeof ApiProductsIdActionsRoute
  '/api/products/$id/toggle': typeof ApiProductsIdToggleRoute
  '/api/providers/$id/actions': typeof ApiProvidersIdActionsRoute
  '/api/providers/$id/activate': typeof ApiProvidersIdActivateRoute
  '/api/providers/$id/deactivate': typeof ApiProvidersIdDeactivateRoute
  '/api/providers/$id/settings': typeof ApiProvidersIdSettingsRoute
  '/api/webhooks/subscribers/$id': typeof ApiWebhooksSubscribersIdRouteWithChildren
  '/api/my/invoices/$id/actions': typeof ApiMyInvoicesIdActionsRoute
  '/api/my/invoices/$id/items': typeof ApiMyInvoicesIdItemsRoute
  '/api/my/invoices/$id/pay': typeof ApiMyInvoicesIdPayRoute
  '/api/my/subscriptions/$id/cancel': typeof ApiMySubscriptionsIdCancelRoute
  '/api/webhooks/subscribers/$id/actions': typeof ApiWebhooksSubscribersIdActionsRoute
  '/api/webhooks/subscribers/$id/toggle': typeof ApiWebhooksSubscribersIdToggleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/audit': typeof ApiAuditRoute
  '/api/health': typeof ApiHealthRoute
  '/api/invoices': typeof ApiInvoicesRouteWithChildren
  '/api/payments': typeof ApiPaymentsRoute
  '/api/products': typeof ApiProductsRouteWithChildren
  '/api/providers': typeof ApiProvidersRouteWithChildren
  '/api/settings': typeof ApiSettingsRoute
  '/api/subscriptions': typeof ApiSubscriptionsRouteWithChildren
  '/api/invoices/$id': typeof ApiInvoicesIdRouteWithChildren
  '/api/my/invoices': typeof ApiMyInvoicesRouteWithChildren
  '/api/my/subscribe': typeof ApiMySubscribeRoute
  '/api/my/subscriptions': typeof ApiMySubscriptionsRouteWithChildren
  '/api/products/$id': typeof ApiProductsIdRouteWithChildren
  '/api/providers/$id': typeof ApiProvidersIdRouteWithChildren
  '/api/subscriptions/$id': typeof ApiSubscriptionsIdRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/api/webhooks/subscribers': typeof ApiWebhooksSubscribersRouteWithChildren
  '/api/invoices/$id/actions': typeof ApiInvoicesIdActionsRoute
  '/api/invoices/$id/cancel': typeof ApiInvoicesIdCancelRoute
  '/api/invoices/$id/items': typeof ApiInvoicesIdItemsRoute
  '/api/invoices/$id/mark-paid': typeof ApiInvoicesIdMarkPaidRoute
  '/api/invoices/$id/refund': typeof ApiInvoicesIdRefundRoute
  '/api/invoices/$id/status': typeof ApiInvoicesIdStatusRoute
  '/api/my/invoices/$id': typeof ApiMyInvoicesIdRouteWithChildren
  '/api/products/$id/actions': typeof ApiProductsIdActionsRoute
  '/api/products/$id/toggle': typeof ApiProductsIdToggleRoute
  '/api/providers/$id/actions': typeof ApiProvidersIdActionsRoute
  '/api/providers/$id/activate': typeof ApiProvidersIdActivateRoute
  '/api/providers/$id/deactivate': typeof ApiProvidersIdDeactivateRoute
  '/api/providers/$id/settings': typeof ApiProvidersIdSettingsRoute
  '/api/webhooks/subscribers/$id': typeof ApiWebhooksSubscribersIdRouteWithChildren
  '/api/my/invoices/$id/actions': typeof ApiMyInvoicesIdActionsRoute
  '/api/my/invoices/$id/items': typeof ApiMyInvoicesIdItemsRoute
  '/api/my/invoices/$id/pay': typeof ApiMyInvoicesIdPayRoute
  '/api/my/subscriptions/$id/cancel': typeof ApiMySubscriptionsIdCancelRoute
  '/api/webhooks/subscribers/$id/actions': typeof ApiWebhooksSubscribersIdActionsRoute
  '/api/webhooks/subscribers/$id/toggle': typeof ApiWebhooksSubscribersIdToggleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/audit'
    | '/api/health'
    | '/api/invoices'
    | '/api/payments'
    | '/api/products'
    | '/api/providers'
    | '/api/settings'
    | '/api/subscriptions'
    | '/api/invoices/$id'
    | '/api/my/invoices'
    | '/api/my/subscribe'
    | '/api/my/subscriptions'
    | '/api/products/$id'
    | '/api/providers/$id'
    | '/api/subscriptions/$id'
    | '/api/webhooks/stripe'
    | '/api/webhooks/subscribers'
    | '/api/invoices/$id/actions'
    | '/api/invoices/$id/cancel'
    | '/api/invoices/$id/items'
    | '/api/invoices/$id/mark-paid'
    | '/api/invoices/$id/refund'
    | '/api/invoices/$id/status'
    | '/api/my/invoices/$id'
    | '/api/products/$id/actions'
    | '/api/products/$id/toggle'
    | '/api/providers/$id/actions'
    | '/api/providers/$id/activate'
    | '/api/providers/$id/deactivate'
    | '/api/providers/$id/settings'
    | '/api/webhooks/subscribers/$id'
    | '/api/my/invoices/$id/actions'
    | '/api/my/invoices/$id/items'
    | '/api/my/invoices/$id/pay'
    | '/api/my/subscriptions/$id/cancel'
    | '/api/webhooks/subscribers/$id/actions'
    | '/api/webhooks/subscribers/$id/toggle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/audit'
    | '/api/health'
    | '/api/invoices'
    | '/api/payments'
    | '/api/products'
    | '/api/providers'
    | '/api/settings'
    | '/api/subscriptions'
    | '/api/invoices/$id'
    | '/api/my/invoices'
    | '/api/my/subscribe'
    | '/api/my/subscriptions'
    | '/api/products/$id'
    | '/api/providers/$id'
    | '/api/subscriptions/$id'
    | '/api/webhooks/stripe'
    | '/api/webhooks/subscribers'
    | '/api/invoices/$id/actions'
    | '/api/invoices/$id/cancel'
    | '/api/invoices/$id/items'
    | '/api/invoices/$id/mark-paid'
    | '/api/invoices/$id/refund'
    | '/api/invoices/$id/status'
    | '/api/my/invoices/$id'
    | '/api/products/$id/actions'
    | '/api/products/$id/toggle'
    | '/api/providers/$id/actions'
    | '/api/providers/$id/activate'
    | '/api/providers/$id/deactivate'
    | '/api/providers/$id/settings'
    | '/api/webhooks/subscribers/$id'
    | '/api/my/invoices/$id/actions'
    | '/api/my/invoices/$id/items'
    | '/api/my/invoices/$id/pay'
    | '/api/my/subscriptions/$id/cancel'
    | '/api/webhooks/subscribers/$id/actions'
    | '/api/webhooks/subscribers/$id/toggle'
  id:
    | '__root__'
    | '/'
    | '/api/audit'
    | '/api/health'
    | '/api/invoices'
    | '/api/payments'
    | '/api/products'
    | '/api/providers'
    | '/api/settings'
    | '/api/subscriptions'
    | '/api/invoices/$id'
    | '/api/my/invoices'
    | '/api/my/subscribe'
    | '/api/my/subscriptions'
    | '/api/products/$id'
    | '/api/providers/$id'
    | '/api/subscriptions/$id'
    | '/api/webhooks/stripe'
    | '/api/webhooks/subscribers'
    | '/api/invoices/$id/actions'
    | '/api/invoices/$id/cancel'
    | '/api/invoices/$id/items'
    | '/api/invoices/$id/mark-paid'
    | '/api/invoices/$id/refund'
    | '/api/invoices/$id/status'
    | '/api/my/invoices/$id'
    | '/api/products/$id/actions'
    | '/api/products/$id/toggle'
    | '/api/providers/$id/actions'
    | '/api/providers/$id/activate'
    | '/api/providers/$id/deactivate'
    | '/api/providers/$id/settings'
    | '/api/webhooks/subscribers/$id'
    | '/api/my/invoices/$id/actions'
    | '/api/my/invoices/$id/items'
    | '/api/my/invoices/$id/pay'
    | '/api/my/subscriptions/$id/cancel'
    | '/api/webhooks/subscribers/$id/actions'
    | '/api/webhooks/subscribers/$id/toggle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAuditRoute: typeof ApiAuditRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiInvoicesRoute: typeof ApiInvoicesRouteWithChildren
  ApiPaymentsRoute: typeof ApiPaymentsRoute
  ApiProductsRoute: typeof ApiProductsRouteWithChildren
  ApiProvidersRoute: typeof ApiProvidersRouteWithChildren
  ApiSettingsRoute: typeof ApiSettingsRoute
  ApiSubscriptionsRoute: typeof ApiSubscriptionsRouteWithChildren
  ApiMyInvoicesRoute: typeof ApiMyInvoicesRouteWithChildren
  ApiMySubscribeRoute: typeof ApiMySubscribeRoute
  ApiMySubscriptionsRoute: typeof ApiMySubscriptionsRouteWithChildren
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute
  ApiWebhooksSubscribersRoute: typeof ApiWebhooksSubscribersRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subscriptions': {
      id: '/api/subscriptions'
      path: '/api/subscriptions'
      fullPath: '/api/subscriptions'
      preLoaderRoute: typeof ApiSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings': {
      id: '/api/settings'
      path: '/api/settings'
      fullPath: '/api/settings'
      preLoaderRoute: typeof ApiSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/providers': {
      id: '/api/providers'
      path: '/api/providers'
      fullPath: '/api/providers'
      preLoaderRoute: typeof ApiProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products': {
      id: '/api/products'
      path: '/api/products'
      fullPath: '/api/products'
      preLoaderRoute: typeof ApiProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments': {
      id: '/api/payments'
      path: '/api/payments'
      fullPath: '/api/payments'
      preLoaderRoute: typeof ApiPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/invoices': {
      id: '/api/invoices'
      path: '/api/invoices'
      fullPath: '/api/invoices'
      preLoaderRoute: typeof ApiInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audit': {
      id: '/api/audit'
      path: '/api/audit'
      fullPath: '/api/audit'
      preLoaderRoute: typeof ApiAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/subscribers': {
      id: '/api/webhooks/subscribers'
      path: '/api/webhooks/subscribers'
      fullPath: '/api/webhooks/subscribers'
      preLoaderRoute: typeof ApiWebhooksSubscribersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/stripe': {
      id: '/api/webhooks/stripe'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subscriptions/$id': {
      id: '/api/subscriptions/$id'
      path: '/$id'
      fullPath: '/api/subscriptions/$id'
      preLoaderRoute: typeof ApiSubscriptionsIdRouteImport
      parentRoute: typeof ApiSubscriptionsRoute
    }
    '/api/providers/$id': {
      id: '/api/providers/$id'
      path: '/$id'
      fullPath: '/api/providers/$id'
      preLoaderRoute: typeof ApiProvidersIdRouteImport
      parentRoute: typeof ApiProvidersRoute
    }
    '/api/products/$id': {
      id: '/api/products/$id'
      path: '/$id'
      fullPath: '/api/products/$id'
      preLoaderRoute: typeof ApiProductsIdRouteImport
      parentRoute: typeof ApiProductsRoute
    }
    '/api/my/subscriptions': {
      id: '/api/my/subscriptions'
      path: '/api/my/subscriptions'
      fullPath: '/api/my/subscriptions'
      preLoaderRoute: typeof ApiMySubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/my/subscribe': {
      id: '/api/my/subscribe'
      path: '/api/my/subscribe'
      fullPath: '/api/my/subscribe'
      preLoaderRoute: typeof ApiMySubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/my/invoices': {
      id: '/api/my/invoices'
      path: '/api/my/invoices'
      fullPath: '/api/my/invoices'
      preLoaderRoute: typeof ApiMyInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/invoices/$id': {
      id: '/api/invoices/$id'
      path: '/$id'
      fullPath: '/api/invoices/$id'
      preLoaderRoute: typeof ApiInvoicesIdRouteImport
      parentRoute: typeof ApiInvoicesRoute
    }
    '/api/webhooks/subscribers/$id': {
      id: '/api/webhooks/subscribers/$id'
      path: '/$id'
      fullPath: '/api/webhooks/subscribers/$id'
      preLoaderRoute: typeof ApiWebhooksSubscribersIdRouteImport
      parentRoute: typeof ApiWebhooksSubscribersRoute
    }
    '/api/providers/$id/settings': {
      id: '/api/providers/$id/settings'
      path: '/settings'
      fullPath: '/api/providers/$id/settings'
      preLoaderRoute: typeof ApiProvidersIdSettingsRouteImport
      parentRoute: typeof ApiProvidersIdRoute
    }
    '/api/providers/$id/deactivate': {
      id: '/api/providers/$id/deactivate'
      path: '/deactivate'
      fullPath: '/api/providers/$id/deactivate'
      preLoaderRoute: typeof ApiProvidersIdDeactivateRouteImport
      parentRoute: typeof ApiProvidersIdRoute
    }
    '/api/providers/$id/activate': {
      id: '/api/providers/$id/activate'
      path: '/activate'
      fullPath: '/api/providers/$id/activate'
      preLoaderRoute: typeof ApiProvidersIdActivateRouteImport
      parentRoute: typeof ApiProvidersIdRoute
    }
    '/api/providers/$id/actions': {
      id: '/api/providers/$id/actions'
      path: '/actions'
      fullPath: '/api/providers/$id/actions'
      preLoaderRoute: typeof ApiProvidersIdActionsRouteImport
      parentRoute: typeof ApiProvidersIdRoute
    }
    '/api/products/$id/toggle': {
      id: '/api/products/$id/toggle'
      path: '/toggle'
      fullPath: '/api/products/$id/toggle'
      preLoaderRoute: typeof ApiProductsIdToggleRouteImport
      parentRoute: typeof ApiProductsIdRoute
    }
    '/api/products/$id/actions': {
      id: '/api/products/$id/actions'
      path: '/actions'
      fullPath: '/api/products/$id/actions'
      preLoaderRoute: typeof ApiProductsIdActionsRouteImport
      parentRoute: typeof ApiProductsIdRoute
    }
    '/api/my/invoices/$id': {
      id: '/api/my/invoices/$id'
      path: '/$id'
      fullPath: '/api/my/invoices/$id'
      preLoaderRoute: typeof ApiMyInvoicesIdRouteImport
      parentRoute: typeof ApiMyInvoicesRoute
    }
    '/api/invoices/$id/status': {
      id: '/api/invoices/$id/status'
      path: '/status'
      fullPath: '/api/invoices/$id/status'
      preLoaderRoute: typeof ApiInvoicesIdStatusRouteImport
      parentRoute: typeof ApiInvoicesIdRoute
    }
    '/api/invoices/$id/refund': {
      id: '/api/invoices/$id/refund'
      path: '/refund'
      fullPath: '/api/invoices/$id/refund'
      preLoaderRoute: typeof ApiInvoicesIdRefundRouteImport
      parentRoute: typeof ApiInvoicesIdRoute
    }
    '/api/invoices/$id/mark-paid': {
      id: '/api/invoices/$id/mark-paid'
      path: '/mark-paid'
      fullPath: '/api/invoices/$id/mark-paid'
      preLoaderRoute: typeof ApiInvoicesIdMarkPaidRouteImport
      parentRoute: typeof ApiInvoicesIdRoute
    }
    '/api/invoices/$id/items': {
      id: '/api/invoices/$id/items'
      path: '/items'
      fullPath: '/api/invoices/$id/items'
      preLoaderRoute: typeof ApiInvoicesIdItemsRouteImport
      parentRoute: typeof ApiInvoicesIdRoute
    }
    '/api/invoices/$id/cancel': {
      id: '/api/invoices/$id/cancel'
      path: '/cancel'
      fullPath: '/api/invoices/$id/cancel'
      preLoaderRoute: typeof ApiInvoicesIdCancelRouteImport
      parentRoute: typeof ApiInvoicesIdRoute
    }
    '/api/invoices/$id/actions': {
      id: '/api/invoices/$id/actions'
      path: '/actions'
      fullPath: '/api/invoices/$id/actions'
      preLoaderRoute: typeof ApiInvoicesIdActionsRouteImport
      parentRoute: typeof ApiInvoicesIdRoute
    }
    '/api/webhooks/subscribers/$id/toggle': {
      id: '/api/webhooks/subscribers/$id/toggle'
      path: '/toggle'
      fullPath: '/api/webhooks/subscribers/$id/toggle'
      preLoaderRoute: typeof ApiWebhooksSubscribersIdToggleRouteImport
      parentRoute: typeof ApiWebhooksSubscribersIdRoute
    }
    '/api/webhooks/subscribers/$id/actions': {
      id: '/api/webhooks/subscribers/$id/actions'
      path: '/actions'
      fullPath: '/api/webhooks/subscribers/$id/actions'
      preLoaderRoute: typeof ApiWebhooksSubscribersIdActionsRouteImport
      parentRoute: typeof ApiWebhooksSubscribersIdRoute
    }
    '/api/my/subscriptions/$id/cancel': {
      id: '/api/my/subscriptions/$id/cancel'
      path: '/$id/cancel'
      fullPath: '/api/my/subscriptions/$id/cancel'
      preLoaderRoute: typeof ApiMySubscriptionsIdCancelRouteImport
      parentRoute: typeof ApiMySubscriptionsRoute
    }
    '/api/my/invoices/$id/pay': {
      id: '/api/my/invoices/$id/pay'
      path: '/pay'
      fullPath: '/api/my/invoices/$id/pay'
      preLoaderRoute: typeof ApiMyInvoicesIdPayRouteImport
      parentRoute: typeof ApiMyInvoicesIdRoute
    }
    '/api/my/invoices/$id/items': {
      id: '/api/my/invoices/$id/items'
      path: '/items'
      fullPath: '/api/my/invoices/$id/items'
      preLoaderRoute: typeof ApiMyInvoicesIdItemsRouteImport
      parentRoute: typeof ApiMyInvoicesIdRoute
    }
    '/api/my/invoices/$id/actions': {
      id: '/api/my/invoices/$id/actions'
      path: '/actions'
      fullPath: '/api/my/invoices/$id/actions'
      preLoaderRoute: typeof ApiMyInvoicesIdActionsRouteImport
      parentRoute: typeof ApiMyInvoicesIdRoute
    }
  }
}

interface ApiInvoicesIdRouteChildren {
  ApiInvoicesIdActionsRoute: typeof ApiInvoicesIdActionsRoute
  ApiInvoicesIdCancelRoute: typeof ApiInvoicesIdCancelRoute
  ApiInvoicesIdItemsRoute: typeof ApiInvoicesIdItemsRoute
  ApiInvoicesIdMarkPaidRoute: typeof ApiInvoicesIdMarkPaidRoute
  ApiInvoicesIdRefundRoute: typeof ApiInvoicesIdRefundRoute
  ApiInvoicesIdStatusRoute: typeof ApiInvoicesIdStatusRoute
}

const ApiInvoicesIdRouteChildren: ApiInvoicesIdRouteChildren = {
  ApiInvoicesIdActionsRoute: ApiInvoicesIdActionsRoute,
  ApiInvoicesIdCancelRoute: ApiInvoicesIdCancelRoute,
  ApiInvoicesIdItemsRoute: ApiInvoicesIdItemsRoute,
  ApiInvoicesIdMarkPaidRoute: ApiInvoicesIdMarkPaidRoute,
  ApiInvoicesIdRefundRoute: ApiInvoicesIdRefundRoute,
  ApiInvoicesIdStatusRoute: ApiInvoicesIdStatusRoute,
}

const ApiInvoicesIdRouteWithChildren = ApiInvoicesIdRoute._addFileChildren(
  ApiInvoicesIdRouteChildren,
)

interface ApiInvoicesRouteChildren {
  ApiInvoicesIdRoute: typeof ApiInvoicesIdRouteWithChildren
}

const ApiInvoicesRouteChildren: ApiInvoicesRouteChildren = {
  ApiInvoicesIdRoute: ApiInvoicesIdRouteWithChildren,
}

const ApiInvoicesRouteWithChildren = ApiInvoicesRoute._addFileChildren(
  ApiInvoicesRouteChildren,
)

interface ApiProductsIdRouteChildren {
  ApiProductsIdActionsRoute: typeof ApiProductsIdActionsRoute
  ApiProductsIdToggleRoute: typeof ApiProductsIdToggleRoute
}

const ApiProductsIdRouteChildren: ApiProductsIdRouteChildren = {
  ApiProductsIdActionsRoute: ApiProductsIdActionsRoute,
  ApiProductsIdToggleRoute: ApiProductsIdToggleRoute,
}

const ApiProductsIdRouteWithChildren = ApiProductsIdRoute._addFileChildren(
  ApiProductsIdRouteChildren,
)

interface ApiProductsRouteChildren {
  ApiProductsIdRoute: typeof ApiProductsIdRouteWithChildren
}

const ApiProductsRouteChildren: ApiProductsRouteChildren = {
  ApiProductsIdRoute: ApiProductsIdRouteWithChildren,
}

const ApiProductsRouteWithChildren = ApiProductsRoute._addFileChildren(
  ApiProductsRouteChildren,
)

interface ApiProvidersIdRouteChildren {
  ApiProvidersIdActionsRoute: typeof ApiProvidersIdActionsRoute
  ApiProvidersIdActivateRoute: typeof ApiProvidersIdActivateRoute
  ApiProvidersIdDeactivateRoute: typeof ApiProvidersIdDeactivateRoute
  ApiProvidersIdSettingsRoute: typeof ApiProvidersIdSettingsRoute
}

const ApiProvidersIdRouteChildren: ApiProvidersIdRouteChildren = {
  ApiProvidersIdActionsRoute: ApiProvidersIdActionsRoute,
  ApiProvidersIdActivateRoute: ApiProvidersIdActivateRoute,
  ApiProvidersIdDeactivateRoute: ApiProvidersIdDeactivateRoute,
  ApiProvidersIdSettingsRoute: ApiProvidersIdSettingsRoute,
}

const ApiProvidersIdRouteWithChildren = ApiProvidersIdRoute._addFileChildren(
  ApiProvidersIdRouteChildren,
)

interface ApiProvidersRouteChildren {
  ApiProvidersIdRoute: typeof ApiProvidersIdRouteWithChildren
}

const ApiProvidersRouteChildren: ApiProvidersRouteChildren = {
  ApiProvidersIdRoute: ApiProvidersIdRouteWithChildren,
}

const ApiProvidersRouteWithChildren = ApiProvidersRoute._addFileChildren(
  ApiProvidersRouteChildren,
)

interface ApiSubscriptionsRouteChildren {
  ApiSubscriptionsIdRoute: typeof ApiSubscriptionsIdRoute
}

const ApiSubscriptionsRouteChildren: ApiSubscriptionsRouteChildren = {
  ApiSubscriptionsIdRoute: ApiSubscriptionsIdRoute,
}

const ApiSubscriptionsRouteWithChildren =
  ApiSubscriptionsRoute._addFileChildren(ApiSubscriptionsRouteChildren)

interface ApiMyInvoicesIdRouteChildren {
  ApiMyInvoicesIdActionsRoute: typeof ApiMyInvoicesIdActionsRoute
  ApiMyInvoicesIdItemsRoute: typeof ApiMyInvoicesIdItemsRoute
  ApiMyInvoicesIdPayRoute: typeof ApiMyInvoicesIdPayRoute
}

const ApiMyInvoicesIdRouteChildren: ApiMyInvoicesIdRouteChildren = {
  ApiMyInvoicesIdActionsRoute: ApiMyInvoicesIdActionsRoute,
  ApiMyInvoicesIdItemsRoute: ApiMyInvoicesIdItemsRoute,
  ApiMyInvoicesIdPayRoute: ApiMyInvoicesIdPayRoute,
}

const ApiMyInvoicesIdRouteWithChildren = ApiMyInvoicesIdRoute._addFileChildren(
  ApiMyInvoicesIdRouteChildren,
)

interface ApiMyInvoicesRouteChildren {
  ApiMyInvoicesIdRoute: typeof ApiMyInvoicesIdRouteWithChildren
}

const ApiMyInvoicesRouteChildren: ApiMyInvoicesRouteChildren = {
  ApiMyInvoicesIdRoute: ApiMyInvoicesIdRouteWithChildren,
}

const ApiMyInvoicesRouteWithChildren = ApiMyInvoicesRoute._addFileChildren(
  ApiMyInvoicesRouteChildren,
)

interface ApiMySubscriptionsRouteChildren {
  ApiMySubscriptionsIdCancelRoute: typeof ApiMySubscriptionsIdCancelRoute
}

const ApiMySubscriptionsRouteChildren: ApiMySubscriptionsRouteChildren = {
  ApiMySubscriptionsIdCancelRoute: ApiMySubscriptionsIdCancelRoute,
}

const ApiMySubscriptionsRouteWithChildren =
  ApiMySubscriptionsRoute._addFileChildren(ApiMySubscriptionsRouteChildren)

interface ApiWebhooksSubscribersIdRouteChildren {
  ApiWebhooksSubscribersIdActionsRoute: typeof ApiWebhooksSubscribersIdActionsRoute
  ApiWebhooksSubscribersIdToggleRoute: typeof ApiWebhooksSubscribersIdToggleRoute
}

const ApiWebhooksSubscribersIdRouteChildren: ApiWebhooksSubscribersIdRouteChildren =
  {
    ApiWebhooksSubscribersIdActionsRoute: ApiWebhooksSubscribersIdActionsRoute,
    ApiWebhooksSubscribersIdToggleRoute: ApiWebhooksSubscribersIdToggleRoute,
  }

const ApiWebhooksSubscribersIdRouteWithChildren =
  ApiWebhooksSubscribersIdRoute._addFileChildren(
    ApiWebhooksSubscribersIdRouteChildren,
  )

interface ApiWebhooksSubscribersRouteChildren {
  ApiWebhooksSubscribersIdRoute: typeof ApiWebhooksSubscribersIdRouteWithChildren
}

const ApiWebhooksSubscribersRouteChildren: ApiWebhooksSubscribersRouteChildren =
  {
    ApiWebhooksSubscribersIdRoute: ApiWebhooksSubscribersIdRouteWithChildren,
  }

const ApiWebhooksSubscribersRouteWithChildren =
  ApiWebhooksSubscribersRoute._addFileChildren(
    ApiWebhooksSubscribersRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAuditRoute: ApiAuditRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiInvoicesRoute: ApiInvoicesRouteWithChildren,
  ApiPaymentsRoute: ApiPaymentsRoute,
  ApiProductsRoute: ApiProductsRouteWithChildren,
  ApiProvidersRoute: ApiProvidersRouteWithChildren,
  ApiSettingsRoute: ApiSettingsRoute,
  ApiSubscriptionsRoute: ApiSubscriptionsRouteWithChildren,
  ApiMyInvoicesRoute: ApiMyInvoicesRouteWithChildren,
  ApiMySubscribeRoute: ApiMySubscribeRoute,
  ApiMySubscriptionsRoute: ApiMySubscriptionsRouteWithChildren,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
  ApiWebhooksSubscribersRoute: ApiWebhooksSubscribersRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
